import 'package:flutter/material.dart';
//final String url_server = 'http://192.168.1.94:5000';
final String url_server = 'https://onlineshop-server.herokuapp.com';
Color ktxtColor = Colors.black;
MaterialColor? kmainColor = Colors.indigo;
const Color kMainColor = Colors.indigo;
Color kaccentColor = Colors.indigoAccent;
Color kbgColor = Colors.white.withOpacity(0.9);
Color kmaintxtColor = Colors.black;
Color ktxtwhiteColor = Colors.white;
Color kColor_active = Colors.red;
